### PR TITLE
Updated dependencies to reduce vulnerabilities

### PR DESCRIPTION
**Pull request by felipecalvo**
I'm planning to release version 0.7.1 with these updated dependencies.

The `dist` folder has a lot of changes after building. Should I commit those @fedescarpa? You say not to in the `readme` but you did commit changes in that folder before.

I'm also adding `package-lock` since it's necessary to do `npm audit` and check for vulnerabilities.

### CODE REVIEW

**Comment by luchotc** [comment]
The dist folder situation explained: https://github.com/mumuki/mumuki-styles/issues/41

**Comment by flbulgarelli** [comment]
¿HOLA? :fearful:

**Comment by flbulgarelli** [comment]
Besides my last comment, are we read to review and merge this PR?

**Comment by felipecalvo** [comment]
Nope, we are testing with @fedescarpa 

Wait till we squash this shit

**Comment by felipecalvo** [comment]
Sooo this branch got a little messier than usual but we're ready to go now.

I've updated dependencies which eliminate half the vulnerabilities, and I've deleted and ignored the dist folder, which is autogenerated when building/installing the dependency anyway. The latter seems trivial but there's a difference between running Grunt tasks as a stand-alone project vs running them as a dependency due to the installing paths npm chooses. This is a [problem](https://github.com/gruntjs/grunt/issues/1211) a [lot](https://stackoverflow.com/questions/22641700/reloading-loading-grunt-tasks-after-grunt-check-dependencies-installs-a-grunt-ta) of [people](https://stackoverflow.com/questions/19795171/how-to-make-grunt-deploy-use-global-npm-modules-instead-of-local-ones?rq=1) seem [to have](https://github.com/gruntjs/grunt-cli/issues/10) with Grunt so I'm using [grunt-loadnpmtasks](https://github.com/JamesMGreene/grunt-loadNpmTasks) to help me solve it.

I think a 0.7.1 tag is the only thing missing. Should I add an empty commit?

**Pull request merged**
